#!/usr/bin/perl -IC:/Users/scman1/AppData/Roaming/DemeterPerl/perl/site/lib
##
## This Demeter-based perl script was generated by Demeter itself.
##
## Beacause this is a machine-generated script, the style will be clunky.
##

use Demeter qw(:ui=screen);

my $prj;
my @params = ();
my @gds    = ();
my @data   = ();
my @paths  = ();

## import data from athena project files
Athena project file C:\harwell\XAS-Workflow-Demo\demeter_workflow\FeS2_dmtr.prj, record 1

## establish Feff objects, SP objects ...
del amp
del enot
del delr
del ss

###__ guess parameters:
push @gds, Demeter::GDS->new(gds => 'guess', name => 'amp', mathexp => '1');
push @gds, Demeter::GDS->new(gds => 'guess', name => 'enot', mathexp => '0');
push @gds, Demeter::GDS->new(gds => 'guess', name => 'delr', mathexp => '0');
push @gds, Demeter::GDS->new(gds => 'guess', name => 'ss', mathexp => '0.1');

## [FeS2] S.1 
push @paths, Demeter::Path -> new(
                                  name    => '[FeS2] S.1 ',
                                  data    => $fzlzg,
                                  parent  => $ianfw,
                                  sp      => >>placeholder<<,
                                  degen   =>  6,
                                  s02     => 'amp',
                                  e0      => 'enot',
                                  delr    => 'delr',
                                  sigma2  => 'ss',
                                  include => 1,
                                 );



@params = (bft_rmin => 1.300, bft_rmax => 2.300, fft_kmin => 3.000, fft_kmax => 12.956,
           fft_dk => 1.000, fft_kwindow => 'Hanning', fit_space => 'r', fit_do_bkg => 0,
           fit_k1 => 1, fit_k2 => 1, fit_k3 => 1);
$fzlzg -> set(@params);
push @data, $fzlzg;

my $fit = Demeter::Fit->new (
                             name        => 'fit to FeS2_xmu',
                             description => 'fit to FeS2_xmu',
   	  		     gds         => \@gds,
			     data        => \@data,
			     paths       => \@paths
			    );
$fit -> fit;
$fit -> logfile("FeS2_xmu.log");
$fit -> freeze(file=>"FeS2_xmu.dpj");
set &screen_echo = 0
show @path 1
set &screen_echo = 0
set &screen_echo = 0
show @path 187
set &screen_echo = 0
set &screen_echo = 0
show @path 188
set &screen_echo = 0
set &screen_echo = 0
show @path 189
set &screen_echo = 0
set &screen_echo = 0
show @path 190
set &screen_echo = 0
set &screen_echo = 0
show @path 191
set &screen_echo = 0
set &screen_echo = 0
show @path 192
set &screen_echo = 0
set &screen_echo = 0
show @path 193
set &screen_echo = 0
set &screen_echo = 0
show @path 194
set &screen_echo = 0
set &screen_echo = 0
show @path 195
set &screen_echo = 0
set &screen_echo = 0
show @path 196
set &screen_echo = 0
set &screen_echo = 0
set &screen_echo = 0
